---

# Scrutinizer CI settings for
# https://scrutinizer-ci.com/g/shalomb/inji/

checks:
  python:
    code_rating: true
    duplicate_code: true

build:
  environment:
    python:
      virtualenv: true
    redis: false
  cache:
    directories:
      - ~/.analysis
      - venv
  dependencies:
    override:
      - echo 'Not installing requirements + package here'
  nodes:
    tests:
  tests:
    before:
      - pip install --upgrade pip coverage
    override:

      - command: py-scrutinizer-run
        idle_timeout: 720

      - command: pylint-run
        idle_timeout: 720
        use_website_config: false

      - command: make venv test-deps install-editable test-cov
        idle_timeout: 720
        coverage:
          file: '.coverage'
          config_file: '.coveragerc'
          format: 'py-cc'

filter:
  excluded_paths:
    - '*/test/*'
    - '*/tests/*'
  dependency_paths:
    - 'lib/*'
