---

language: python

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev

cache:
  pip: true
  directories:
    - $HOME/.cache/pip
    - venv/

before_script:
  - make clean
  - make venv-deps venv
  - make test-deps

script:
  - make install-editable
  - make test-durations test-cov
  - make install-build run

after_success:
  - true
