name: Security Checks

on:
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run security checks weekly on Mondays at 10:00 UTC
    - cron: '0 10 * * 1'

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python 3.12
      run: uv python install 3.12

    - name: Install dependencies
      run: make sync

    - name: Run pip-audit for vulnerability scanning
      run: |
        uv add --dev pip-audit
        uv run pip-audit --require-hashes --desc

    - name: Check for known security issues with safety
      run: |
        uv add --dev safety
        uv run safety check --json || echo "Safety check completed with warnings"

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: moderate